{"level":"info","ts":"2022-12-02T21:15:00.605+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"localhost"}
{"level":"info","ts":"2022-12-02T21:15:00.668+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Exec","sql":";","args":[],"time":0.0042272,"commandTag":"","pid":276}
{"level":"info","ts":"2022-12-02T22:00:36.127+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"79.137.198.139"}
{"level":"error","ts":"2022-12-02T22:00:36.260+0300","caller":"v4@v4.17.2/conn.go:354","msg":"connect failed","err":"failed to connect to `host=79.137.198.139 user=postgres database=user_service`: failed to receive message (read tcp 192.168.0.111:63624->79.137.198.139:5420: wsarecv: An existing connection was forcibly closed by the remote host.)","stacktrace":"github.com/jackc/pgx/v4.(*Conn).log\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:354\ngithub.com/jackc/pgx/v4.connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:225\ngithub.com/jackc/pgx/v4.ConnectConfig\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:113\ngithub.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/stdlib/sql.go:285\ndatabase/sql.(*DB).conn\n\tC:/Program Files/Go/src/database/sql/sql.go:1395\ndatabase/sql.(*DB).PingContext\n\tC:/Program Files/Go/src/database/sql/sql.go:853\ndatabase/sql.(*DB).Ping\n\tC:/Program Files/Go/src/database/sql/sql.go:875\ngit.friends.com/PetLand/UserService/v2/internal/store/db.NewDB\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/store/db/dbutil.go:46\ngit.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:37\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"fatal","ts":"2022-12-02T22:00:36.263+0300","caller":"service/userService.go:39","msg":"Can't initialize connection to database{error 26 0  Unavailable resource}","stacktrace":"git.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:39\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"info","ts":"2022-12-02T22:01:07.384+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"79.137.198.139"}
{"level":"error","ts":"2022-12-02T22:01:07.523+0300","caller":"v4@v4.17.2/conn.go:354","msg":"connect failed","err":"failed to connect to `host=79.137.198.139 user=postgres database=user_service`: failed to receive message (read tcp 192.168.0.111:63631->79.137.198.139:5420: wsarecv: An existing connection was forcibly closed by the remote host.)","stacktrace":"github.com/jackc/pgx/v4.(*Conn).log\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:354\ngithub.com/jackc/pgx/v4.connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:225\ngithub.com/jackc/pgx/v4.ConnectConfig\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:113\ngithub.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/stdlib/sql.go:285\ndatabase/sql.(*DB).conn\n\tC:/Program Files/Go/src/database/sql/sql.go:1395\ndatabase/sql.(*DB).PingContext\n\tC:/Program Files/Go/src/database/sql/sql.go:853\ndatabase/sql.(*DB).Ping\n\tC:/Program Files/Go/src/database/sql/sql.go:875\ngit.friends.com/PetLand/UserService/v2/internal/store/db.NewDB\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/store/db/dbutil.go:46\ngit.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:37\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"fatal","ts":"2022-12-02T22:01:07.527+0300","caller":"service/userService.go:39","msg":"Can't initialize connection to database{error 26 0  Unavailable resource}","stacktrace":"git.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:39\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"info","ts":"2022-12-02T22:01:44.739+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"localhost"}
{"level":"info","ts":"2022-12-02T22:01:44.769+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Exec","args":[],"time":0.0011941,"commandTag":"","pid":45,"sql":";"}
{"level":"info","ts":"2022-12-02T22:05:53.563+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"79.137.198.139"}
{"level":"error","ts":"2022-12-02T22:05:54.301+0300","caller":"v4@v4.17.2/conn.go:354","msg":"connect failed","err":"failed to connect to `host=79.137.198.139 user=postgres database=user_service`: server error (FATAL: database \"user_service\" does not exist (SQLSTATE 3D000))","stacktrace":"github.com/jackc/pgx/v4.(*Conn).log\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:354\ngithub.com/jackc/pgx/v4.connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:225\ngithub.com/jackc/pgx/v4.ConnectConfig\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:113\ngithub.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/stdlib/sql.go:285\ndatabase/sql.(*DB).conn\n\tC:/Program Files/Go/src/database/sql/sql.go:1395\ndatabase/sql.(*DB).PingContext\n\tC:/Program Files/Go/src/database/sql/sql.go:853\ndatabase/sql.(*DB).Ping\n\tC:/Program Files/Go/src/database/sql/sql.go:875\ngit.friends.com/PetLand/UserService/v2/internal/store/db.NewDB\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/store/db/dbutil.go:46\ngit.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:37\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"fatal","ts":"2022-12-02T22:05:54.302+0300","caller":"service/userService.go:39","msg":"Can't initialize connection to database{error 26 0  Unavailable resource}","stacktrace":"git.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:39\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"info","ts":"2022-12-02T22:22:07.005+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"79.137.198.139"}
{"level":"error","ts":"2022-12-02T22:22:07.322+0300","caller":"v4@v4.17.2/conn.go:354","msg":"connect failed","err":"failed to connect to `host=79.137.198.139 user=postgres database=user_service`: server error (FATAL: database \"user_service\" does not exist (SQLSTATE 3D000))","stacktrace":"github.com/jackc/pgx/v4.(*Conn).log\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:354\ngithub.com/jackc/pgx/v4.connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:225\ngithub.com/jackc/pgx/v4.ConnectConfig\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:113\ngithub.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/stdlib/sql.go:285\ndatabase/sql.(*DB).conn\n\tC:/Program Files/Go/src/database/sql/sql.go:1395\ndatabase/sql.(*DB).PingContext\n\tC:/Program Files/Go/src/database/sql/sql.go:853\ndatabase/sql.(*DB).Ping\n\tC:/Program Files/Go/src/database/sql/sql.go:875\ngit.friends.com/PetLand/UserService/v2/internal/store/db.NewDB\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/store/db/dbutil.go:46\ngit.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:37\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"fatal","ts":"2022-12-02T22:22:07.324+0300","caller":"service/userService.go:39","msg":"Can't initialize connection to database{error 26 0  Unavailable resource}","stacktrace":"git.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:39\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"info","ts":"2022-12-02T22:29:26.809+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"localhost"}
{"level":"error","ts":"2022-12-02T22:29:27.004+0300","caller":"v4@v4.17.2/conn.go:354","msg":"connect failed","err":"failed to connect to `host=localhost user=postgres database=user_service`: failed SASL auth (FATAL: password authentication failed for user \"postgres\" (SQLSTATE 28P01))","stacktrace":"github.com/jackc/pgx/v4.(*Conn).log\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:354\ngithub.com/jackc/pgx/v4.connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:225\ngithub.com/jackc/pgx/v4.ConnectConfig\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:113\ngithub.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/stdlib/sql.go:285\ndatabase/sql.(*DB).conn\n\tC:/Program Files/Go/src/database/sql/sql.go:1395\ndatabase/sql.(*DB).PingContext\n\tC:/Program Files/Go/src/database/sql/sql.go:853\ndatabase/sql.(*DB).Ping\n\tC:/Program Files/Go/src/database/sql/sql.go:875\ngit.friends.com/PetLand/UserService/v2/internal/store/db.NewDB\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/store/db/dbutil.go:46\ngit.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:37\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"fatal","ts":"2022-12-02T22:29:27.007+0300","caller":"service/userService.go:39","msg":"Can't initialize connection to database{error 26 0  Unavailable resource}","stacktrace":"git.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:39\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"info","ts":"2022-12-02T22:30:05.293+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"localhost"}
{"level":"info","ts":"2022-12-02T22:30:05.329+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Exec","commandTag":"","pid":135,"sql":";","args":[],"time":0.0010014}
{"level":"info","ts":"2022-12-02T22:34:40.374+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"localhost"}
{"level":"info","ts":"2022-12-02T22:34:40.396+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Exec","sql":";","args":[],"time":0.0006598,"commandTag":"","pid":145}
{"level":"info","ts":"2022-12-02T22:38:56.063+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"79.137.198.139"}
{"level":"error","ts":"2022-12-02T22:38:56.206+0300","caller":"v4@v4.17.2/conn.go:354","msg":"connect failed","err":"failed to connect to `host=79.137.198.139 user=postgres database=user_service`: failed to receive message (read tcp 192.168.0.111:63118->79.137.198.139:5420: wsarecv: An existing connection was forcibly closed by the remote host.)","stacktrace":"github.com/jackc/pgx/v4.(*Conn).log\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:354\ngithub.com/jackc/pgx/v4.connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:225\ngithub.com/jackc/pgx/v4.ConnectConfig\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/conn.go:113\ngithub.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect\n\tC:/Users/alext/go/pkg/mod/github.com/jackc/pgx/v4@v4.17.2/stdlib/sql.go:285\ndatabase/sql.(*DB).conn\n\tC:/Program Files/Go/src/database/sql/sql.go:1395\ndatabase/sql.(*DB).PingContext\n\tC:/Program Files/Go/src/database/sql/sql.go:853\ndatabase/sql.(*DB).Ping\n\tC:/Program Files/Go/src/database/sql/sql.go:875\ngit.friends.com/PetLand/UserService/v2/internal/store/db.NewDB\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/store/db/dbutil.go:46\ngit.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:37\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"fatal","ts":"2022-12-02T22:38:56.208+0300","caller":"service/userService.go:39","msg":"Can't initialize connection to database{error 26 0  Unavailable resource}","stacktrace":"git.friends.com/PetLand/UserService/v2/internal/service.(*service).Start\n\tC:/Users/alext/git.friends.com/PetLand/UserService/internal/service/userService.go:39\nmain.main\n\tC:/Users/alext/git.friends.com/PetLand/UserService/cmd/main.go:15\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:250"}
{"level":"info","ts":"2022-12-02T22:39:12.406+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Dialing PostgreSQL server","host":"79.137.198.139"}
{"level":"info","ts":"2022-12-02T22:39:12.810+0300","caller":"v4@v4.17.2/conn.go:354","msg":"Exec","pid":72,"sql":";","args":[],"time":0.0801892,"commandTag":""}
{"level":"info","ts":"2022-12-02T22:42:12.816+0300","caller":"v4@v4.17.2/conn.go:354","msg":"closed connection","pid":72}
